export { ReactComponent as ICEdit } from './edit.svg';
export { ReactComponent as ICClose } from './ic_close.svg';
export { ReactComponent as ICLockOn } from './Lock on.svg';
export { ReactComponent as ICMailFill } from './IcMailFill.svg';
export { ReactComponent as ICBtnLiveContent } from './_btn_live contents.svg';
export { ReactComponent as ICArrow } from './Arrow_down.svg';
export { ReactComponent as ICBtnAdd } from './btn_add_big.svg';
export { ReactComponent as ICBtnShare } from './btn_share.svg';
export { ReactComponent as ICAdobe } from './ic_adobe.svg';
export { ReactComponent as ICBehance } from './ic_behance.svg';
export { ReactComponent as ICDropDown } from './ic_dropdown.svg';
export { ReactComponent as ICEyeOff } from './ic_eyeoff.svg';
export { ReactComponent as ICFavorite } from './ic_favorite_fill_24.svg';
export { ReactComponent as ICFolder } from './ic_folder.svg';
export { ReactComponent as ICGlass } from './ic_glass.svg';
export { ReactComponent as ICHomePreview } from './ic_home_preview.svg';
export { ReactComponent as ICPerson } from './ic_person_fill_24.svg';
export { ReactComponent as ICRecommand } from './ic_recommend.svg';
export { ReactComponent as ICSearch } from './ic_search.svg';
export { ReactComponent as ICSearchBarHover } from './ic_searchHover.svg';
export { ReactComponent as ICStar } from './ic_star_fill_24.svg';
export { ReactComponent as ICThumbsUp } from './ic_Tumbsup.svg';
export { ReactComponent as ICVisible } from './ic_visible_fill.svg';
export { ReactComponent as ICAlertFill } from './IcAlertFill.svg';
export { ReactComponent as ICMailFill } from './IcMailFii.svg';
export { ReactComponent as ICLineCol } from './Line 5.svg';
export { ReactComponent as ICBtnNext } from './Next button.svg';
